// MatFree Engine - Built-in Documentation System

export interface HelpEntry {
  name: string
  syntax: string
  description: string
  category: string
  examples?: string[]
}

const docs: Map<string, HelpEntry> = new Map()

function doc(name: string, syntax: string, description: string, category: string, examples?: string[]) {
  docs.set(name, { name, syntax, description, category, examples })
}

// Math
doc('sin', 'sin(x)', 'Sine of x (radians)', 'Math', ['sin(pi/2)  % = 1'])
doc('cos', 'cos(x)', 'Cosine of x (radians)', 'Math', ['cos(0)  % = 1'])
doc('tan', 'tan(x)', 'Tangent of x (radians)', 'Math')
doc('asin', 'asin(x)', 'Inverse sine (radians)', 'Math')
doc('acos', 'acos(x)', 'Inverse cosine (radians)', 'Math')
doc('atan', 'atan(x)', 'Inverse tangent (radians)', 'Math')
doc('atan2', 'atan2(y, x)', 'Four-quadrant inverse tangent', 'Math')
doc('sinh', 'sinh(x)', 'Hyperbolic sine', 'Math')
doc('cosh', 'cosh(x)', 'Hyperbolic cosine', 'Math')
doc('tanh', 'tanh(x)', 'Hyperbolic tangent', 'Math')
doc('exp', 'exp(x)', 'Exponential e^x', 'Math', ['exp(1)  % = 2.7183'])
doc('log', 'log(x)', 'Natural logarithm', 'Math')
doc('log2', 'log2(x)', 'Base-2 logarithm', 'Math')
doc('log10', 'log10(x)', 'Base-10 logarithm', 'Math')
doc('sqrt', 'sqrt(x)', 'Square root', 'Math', ['sqrt(16)  % = 4'])
doc('abs', 'abs(x)', 'Absolute value / complex magnitude', 'Math')
doc('real', 'real(z)', 'Real part of complex number or array', 'Math', ['real(3+4i)  % = 3'])
doc('imag', 'imag(z)', 'Imaginary part of complex number or array', 'Math', ['imag(3+4i)  % = 4'])
doc('conj', 'conj(z)', 'Complex conjugate', 'Math', ['conj(3+4i)'])
doc('angle', 'angle(z)', 'Argument (phase) of complex number in radians', 'Math')
doc('ceil', 'ceil(x)', 'Round toward positive infinity', 'Math')
doc('floor', 'floor(x)', 'Round toward negative infinity', 'Math')
doc('round', 'round(x)', 'Round to nearest integer', 'Math')
doc('fix', 'fix(x)', 'Round toward zero', 'Math')
doc('mod', 'mod(a, b)', 'Modulus after division', 'Math')
doc('rem', 'rem(a, b)', 'Remainder after division', 'Math')
doc('sign', 'sign(x)', 'Signum function (-1, 0, or 1)', 'Math')
doc('max', 'max(x) or max(a, b)', 'Maximum value', 'Math', ['max([3 1 4])  % = 4'])
doc('min', 'min(x) or min(a, b)', 'Minimum value', 'Math')
doc('sum', 'sum(x)', 'Sum of array elements', 'Math', ['sum([1 2 3])  % = 6'])
doc('prod', 'prod(x)', 'Product of array elements', 'Math')
doc('cumsum', 'cumsum(x)', 'Cumulative sum', 'Math')
doc('cumprod', 'cumprod(x)', 'Cumulative product', 'Math')

// Matrix
doc('zeros', 'zeros(n) or zeros(r,c)', 'Create matrix of zeros', 'Matrix', ['zeros(3)  % 3x3 zeros'])
doc('ones', 'ones(n) or ones(r,c)', 'Create matrix of ones', 'Matrix')
doc('eye', 'eye(n)', 'Identity matrix', 'Matrix', ['eye(3)'])
doc('rand', 'rand(n) or rand(r,c)', 'Uniformly distributed random numbers', 'Matrix')
doc('randn', 'randn(n) or randn(r,c)', 'Normally distributed random numbers', 'Matrix')
doc('randperm', 'randperm(n) or randperm(n, k)', 'Random permutation of 1..n (or k of them)', 'Matrix')
doc('randi', 'randi(imax) or randi([imin imax], [r c])', 'Uniform random integers in range', 'Matrix')
doc('rng', "rng(seed) or rng('shuffle')", 'Control random number generator seed', 'Matrix')
doc('linspace', 'linspace(a, b, n)', 'Generate n linearly spaced points from a to b', 'Matrix', ['linspace(0, 1, 5)'])
doc('logspace', 'logspace(a, b, n)', 'Generate n logarithmically spaced points from 10^a to 10^b', 'Matrix')
doc('size', 'size(A)', 'Matrix dimensions [rows cols]', 'Matrix')
doc('length', 'length(A)', 'Length of largest dimension', 'Matrix')
doc('numel', 'numel(A)', 'Number of elements', 'Matrix')
doc('reshape', 'reshape(A, r, c)', 'Reshape matrix to r-by-c', 'Matrix')
doc('diag', 'diag(v) or diag(A)', 'Create diagonal matrix or extract diagonal', 'Matrix')
doc('repmat', 'repmat(A, r, c)', 'Replicate and tile matrix', 'Matrix')
doc('fliplr', 'fliplr(A)', 'Flip matrix left-right', 'Matrix')
doc('flipud', 'flipud(A)', 'Flip matrix up-down', 'Matrix')
doc('rot90', 'rot90(A, k)', 'Rotate matrix 90 degrees k times', 'Matrix')
doc('magic', 'magic(n)', 'Magic square of order n', 'Matrix', ['magic(3)'])
doc('kron', 'kron(A, B)', 'Kronecker tensor product', 'Matrix')
doc('triu', 'triu(A)', 'Upper triangular part', 'Matrix')
doc('tril', 'tril(A)', 'Lower triangular part', 'Matrix')
doc('meshgrid', 'meshgrid(x, y)', 'Generate 2D grid coordinates', 'Matrix')
doc('vander', 'vander(v, n)', 'Vandermonde matrix', 'Matrix')

// Linear Algebra
doc('det', 'det(A)', 'Matrix determinant', 'Linear Algebra', ['det([1 2; 3 4])  % = -2'])
doc('inv', 'inv(A)', 'Matrix inverse', 'Linear Algebra')
doc('trace', 'trace(A)', 'Sum of diagonal elements', 'Linear Algebra')
doc('norm', 'norm(A)', 'Matrix or vector norm', 'Linear Algebra')
doc('rank', 'rank(A)', 'Matrix rank', 'Linear Algebra')
doc('eig', 'eig(A)', 'Eigenvalues of square matrix', 'Linear Algebra', ['eig([2 1; 1 2])'])
doc('svd', 'svd(A)', 'Singular value decomposition', 'Linear Algebra')
doc('cond', 'cond(A) or cond(A, p)', 'Condition number (p=1,2,inf,"fro"); default 2-norm via SVD', 'Linear Algebra')
doc('rcond', 'rcond(A)', 'Reciprocal condition number estimate', 'Linear Algebra')
doc('pinv', 'pinv(A)', 'Moore-Penrose pseudoinverse', 'Linear Algebra')
doc('lu', 'lu(A)', 'LU factorization: {L, U} = lu(A)', 'Linear Algebra')
doc('qr', 'qr(A)', 'QR factorization: {Q, R} = qr(A)', 'Linear Algebra')
doc('chol', 'chol(A)', 'Cholesky factorization', 'Linear Algebra')
doc('linsolve', 'linsolve(A, b)', 'Solve linear system Ax = b', 'Linear Algebra')
doc('dot', 'dot(a, b)', 'Dot product', 'Linear Algebra')
doc('cross', 'cross(a, b)', 'Cross product (3D vectors)', 'Linear Algebra')

// Statistics
doc('mean', 'mean(x)', 'Arithmetic mean', 'Statistics', ['mean([1 2 3 4])  % = 2.5'])
doc('median', 'median(x)', 'Median value', 'Statistics')
doc('std', 'std(x)', 'Standard deviation', 'Statistics')
doc('var', 'var(x)', 'Variance', 'Statistics')
doc('mvnrnd', 'mvnrnd(mu, Sigma, n)', 'Multivariate normal random samples', 'Statistics')
doc('randsample', 'randsample(n, k) or randsample(pop, k)', 'Random sample with replacement', 'Statistics')
doc('bootstrp', 'bootstrp(nboot, @stat, data)', 'Bootstrap replicates of a statistic', 'Statistics')
doc('quantile', 'quantile(x, p)', 'Quantile(s) of data for p in [0,1]', 'Statistics')
doc('prctile', 'prctile(x, p)', 'Percentile(s) of data for p in [0,100]', 'Statistics')
doc('sort', 'sort(x)', 'Sort in ascending order', 'Statistics')
doc('normpdf', 'normpdf(x, mu, sigma)', 'Normal probability density function', 'Statistics')
doc('normcdf', 'normcdf(x, mu, sigma)', 'Normal cumulative distribution function', 'Statistics')
doc('norminv', 'norminv(p, mu, sigma)', 'Inverse normal CDF (quantile function)', 'Statistics')
doc('hist', 'hist(data, nbins)', 'Plot histogram', 'Statistics')
doc('kmeans', 'kmeans(X, k)', 'K-means clustering (returns labels)', 'Statistics')
doc('pca', '[coeff,score,latent] = pca(X)', 'Principal component analysis (educational)', 'Statistics')
doc('regress', 'b = regress(y, X)', 'Multiple linear regression coefficients', 'Statistics')

// Plotting
doc('plot', "plot(x, y) or plot(x, y, 'r--')", 'Plot line chart. Line specs: colors (r,g,b,k), styles (--,:,-.), markers (o,s,d,^,x,+)', 'Plotting', ["x = linspace(0, 2*pi, 100);\nplot(x, sin(x), 'b')\ntitle('Sine Wave')"])
doc('scatter', 'scatter(x, y, sz)', 'Create scatter plot', 'Plotting')
doc('bar', 'bar(x, y)', 'Create bar chart', 'Plotting')
doc('stem', 'stem(x, y)', 'Discrete sequence plot', 'Plotting')
doc('stairs', 'stairs(x, y)', 'Stairstep plot', 'Plotting')
doc('area', 'area(x, y)', 'Filled area plot', 'Plotting')
doc('semilogx', 'semilogx(x, y)', 'Semi-log plot (log x-axis)', 'Plotting')
doc('semilogy', 'semilogy(x, y)', 'Semi-log plot (log y-axis)', 'Plotting')
doc('loglog', 'loglog(x, y)', 'Log-log plot', 'Plotting')
doc('polar_plot', 'polar_plot(theta, r)', 'Polar coordinate plot', 'Plotting')
doc('pie_chart', 'pie_chart(data)', 'Pie chart', 'Plotting')
doc('imagesc', 'imagesc(A)', 'Display matrix as heatmap image', 'Plotting', ['A = magic(10);\nimagesc(A)\ntitle(\'Magic Square\')'])
doc('conv2', 'conv2(A, K)', '2D convolution of matrix with kernel', 'Image')
doc('fspecial', "fspecial('gaussian', sz, sigma)", 'Create 2D filter kernels (gaussian, average)', 'Image')
doc('imfilter', 'imfilter(A, H)', 'Filter image/matrix with kernel (same size, zero pad)', 'Image')
doc('imresize', 'imresize(A, scale) or imresize(A, [r c])', 'Resize matrix/image (nearest lite)', 'Image')
doc('edge', 'edge(A)', 'Edge magnitude via Sobel (lite)', 'Image')
doc('contour', "contour(X, Y, Z)", 'Contour plot of matrix data', 'Plotting')
doc('errorbar', 'errorbar(x, y, e) or errorbar(y, e)', 'Line plot with vertical error bars', 'Plotting')
doc('quiver', 'quiver(x, y, u, v)', 'Quiver / vector field plot', 'Plotting')
doc('boxplot', 'boxplot(data)', 'Box plot (matrix columns as groups)', 'Plotting')
doc('spy', 'spy(A)', 'Sparsity pattern scatter plot', 'Plotting')
doc('title', "title('text')", 'Set plot title', 'Plotting')
doc('xlabel', "xlabel('text')", 'Set x-axis label', 'Plotting')
doc('ylabel', "ylabel('text')", 'Set y-axis label', 'Plotting')
doc('legend', "legend('a', 'b')", 'Add legend to plot', 'Plotting')
doc('grid', "grid('on') or grid('off')", 'Toggle grid lines', 'Plotting')
doc('hold', "hold('on') or hold('off')", 'Hold current plot for overlaying', 'Plotting')
doc('figure', 'figure(n)', 'Create or switch to figure n', 'Plotting')
doc('clf', 'clf', 'Clear current figure', 'Plotting')
doc('xlim', 'xlim([lo hi])', 'Set x-axis limits', 'Plotting')
doc('ylim', 'ylim([lo hi])', 'Set y-axis limits', 'Plotting')

// Scientific
doc('fft', 'fft(x)', 'Fast Fourier Transform', 'Signal Processing', ['x = sin(linspace(0, 4*pi, 64));\nplot(abs_fft(x))'])
doc('ifft', 'ifft(X)', 'Inverse Fast Fourier Transform', 'Signal Processing')
doc('fftshift', 'fftshift(X)', 'Shift zero-frequency to center', 'Signal Processing')
doc('conv', 'conv(u, v)', 'Convolution of two vectors', 'Signal Processing')
doc('deconv', 'deconv(u, v)', 'Deconvolution', 'Signal Processing')
doc('filter', 'filter(b, a, x)', 'Apply digital filter', 'Signal Processing')
doc('polyval', 'polyval(p, x)', 'Evaluate polynomial p at points x', 'Polynomials', ['polyval([1 0 -1], 2)  % = 3 (x^2 - 1 at x=2)'])
doc('polyfit', 'polyfit(x, y, n)', 'Polynomial curve fitting (degree n)', 'Polynomials')
doc('roots', 'roots(p)', 'Polynomial roots', 'Polynomials', ['roots([1 0 -1])  % = [1, -1]'])
doc('poly', 'poly(r)', 'Polynomial from roots', 'Polynomials')
doc('polyder', 'polyder(p)', 'Polynomial derivative', 'Polynomials')
doc('polyint', 'polyint(p)', 'Polynomial integration', 'Polynomials')
doc('interp1', "interp1(x, y, xq, 'linear')", 'Linear interpolation', 'Interpolation')
doc('spline', 'spline(x, y, xq)', 'Cubic spline interpolation', 'Interpolation')
doc('diff', 'diff(x)', 'Differences between adjacent elements', 'Calculus')
doc('gradient', 'gradient(y, h)', 'Numerical gradient', 'Calculus')
doc('trapz', 'trapz(x, y)', 'Trapezoidal numerical integration', 'Calculus', ['trapz([0 1], [0 1])  % = 0.5'])
doc('cumtrapz', 'cumtrapz(x, y)', 'Cumulative trapezoidal integration', 'Calculus')
doc('integral', 'integral(@(x) f(x), a, b)', 'Adaptive numerical integration', 'Calculus', ['integral(@(x) x.^2, 0, 1)  % = 0.3333'])
doc('ode45', 'ode45(@(t,y) f, [t0 tf], y0)', 'Solve ODE using Runge-Kutta 4th order', 'Differential Equations', ["% Solve y' = -y\nresult = ode45(@(t,y) -y, [0 5], [1]);\nt = result{1}; y = result{2};\nplot(t, y)"])
doc('fminsearch', 'fminsearch(@(x) f(x), x0)', 'Find minimum using Nelder-Mead simplex', 'Optimization')
doc('fzero', 'fzero(@(x) f(x), x0)', 'Find root of scalar function', 'Optimization')
doc('lsqcurvefit', 'lsqcurvefit(@model, p0, xdata, ydata)', 'Nonlinear least-squares fit of model(p,x) to (xdata,ydata)', 'Optimization')
doc('lsqnonlin', 'lsqnonlin(@residuals, x0)', 'Nonlinear least-squares on vector residuals', 'Optimization')
doc('fminbnd', 'fminbnd(@(x) f(x), x1, x2)', 'Bounded scalar minimization (golden section)', 'Optimization')
doc('fsolve', 'fsolve(@(x) F(x), x0)', 'Solve F(x)=0 for small systems', 'Optimization')
doc('gamma', 'gamma(x)', 'Gamma function', 'Special Functions')
doc('beta', 'beta(a, b)', 'Beta function', 'Special Functions')
doc('erf', 'erf(x)', 'Error function', 'Special Functions')
doc('erfc', 'erfc(x)', 'Complementary error function', 'Special Functions')
doc('besselj', 'besselj(nu, x)', 'Bessel function of the first kind', 'Special Functions')
doc('bessely', 'bessely(nu, x)', 'Bessel function of the second kind (approx)', 'Special Functions')
doc('besseli', 'besseli(nu, x)', 'Modified Bessel first kind (approx)', 'Special Functions')
doc('besselk', 'besselk(nu, x)', 'Modified Bessel second kind (approx)', 'Special Functions')
doc('gammaln', 'gammaln(x)', 'Logarithm of gamma function', 'Special Functions')
doc('psi', 'psi(x)', 'Digamma function (derivative of log gamma)', 'Special Functions')
doc('erfcinv', 'erfcinv(y)', 'Inverse complementary error function', 'Special Functions')
doc('airy', 'airy(x)', 'Airy function Ai(x) (approx)', 'Special Functions')
doc('ellipke', 'ellipke(m) or [K,E]=ellipke(m)', 'Complete elliptic integrals K(m), E(m) (approx)', 'Special Functions')
doc('legendre', 'legendre(n, x)', 'Legendre polynomial P_n(x) for low n', 'Special Functions')

// I/O
doc('disp', 'disp(x)', 'Display value', 'I/O')
doc('fprintf', "fprintf(fmt, ...)", 'Formatted output (like C printf)', 'I/O', ["fprintf('x = %d\\n', 42)"])
doc('sprintf', "sprintf(fmt, ...)", 'Formatted string (returns string)', 'I/O')
doc('readcsv', "readcsv('text') or readcsv('text','header')", 'Parse CSV (quoted fields, missing->NaN); header skips first line', 'I/O', ["data = readcsv('1,2,3\\n4,5,6')", "T = readcsv('h1,h2\\n1,2','header')"])
doc('readtable', "readtable('csvtext') or readtable(..., 'header')", 'CSV to struct with column vectors (headers as fields)', 'I/O')
doc('writetable', "writetable(T) or writetable(T,'file.csv')", 'Struct of columns to CSV (with headers)', 'I/O')
doc('save', "save('file.mat.json')", 'Save workspace snapshot as JSON (browser download)', 'I/O')
doc('load', "load('json')", 'Load JSON into struct or value (lite .mat-style)', 'I/O')
doc('writematrix', 'writematrix(A) or writematrix(A, filename)', 'Matrix to CSV string; with filename triggers browser download', 'I/O', ['writematrix([1 2; 3 4], "data.csv")'])
doc('writecsv', 'writecsv(A) or writecsv(A, filename)', 'Same as writematrix', 'I/O')
doc('jsondecode', "jsondecode('string')", 'Parse JSON string to struct or cell', 'I/O', ["s = jsondecode('{\"x\":1,\"y\":2}')"])
doc('jsonencode', 'jsonencode(val)', 'Convert struct, cell, or matrix to JSON string', 'I/O', ['jsonencode(struct("a", 1, "b", 2))'])

// Utility
doc('tic', 'tic', 'Start stopwatch timer', 'Utility')
doc('toc', 'toc', 'Read elapsed time from tic', 'Utility')
doc('whos', 'whos', 'List workspace variables', 'Utility')
doc('clear', 'clear', 'Clear workspace', 'Utility')
doc('exist', "exist('name')", 'Check if variable/function exists', 'Utility')

// Symbolic Math
doc('sym', "sym('expr')", 'Create symbolic expression', 'Symbolic Math')
doc('symdiff', "symdiff('expr', 'var')", 'Symbolic differentiation with chain rule, product rule, quotient rule', 'Symbolic Math', ["symdiff('x^3', 'x')", "symdiff('sin(x^2)', 'x')", "symdiff('x^3', 'x', 2)"])
doc('symint', "symint('expr', 'var')", 'Symbolic integration for polynomials, trig, exp, log', 'Symbolic Math', ["symint('x^2', 'x')", "symint('sin(x)', 'x')"])
doc('symsolve', "symsolve('expr', 'var')", 'Solve equations symbolically (linear, quadratic, polynomial via Newton)', 'Symbolic Math', ["symsolve('x^2 - 5*x + 6', 'x')"])
doc('symsimplify', "symsimplify('expr')", 'Simplify symbolic expression algebraically', 'Symbolic Math')
doc('symexpand', "symexpand('expr')", 'Expand symbolic expression (distribute products, powers)', 'Symbolic Math', ["symexpand('(x+1)^3')"])
doc('symsubs', "symsubs('expr', 'var', val)", 'Substitute variable in symbolic expression', 'Symbolic Math', ["symsubs('x^2 + 1', 'x', 3)"])
doc('symtaylor', "symtaylor('expr', 'var', center, order)", 'Compute Taylor series expansion', 'Symbolic Math', ["symtaylor('sin(x)', 'x', 0, 7)"])
doc('symeval', "symeval('expr', 'var', val)", 'Evaluate symbolic expression numerically', 'Symbolic Math')
doc('symplot', "symplot('expr', 'var', [lo hi])", 'Plot symbolic expression over range', 'Symbolic Math')

// Matrix Functions
doc('expm', 'expm(A)', 'Matrix exponential via Padé approximation with scaling/squaring', 'Linear Algebra')
doc('logm', 'logm(A)', 'Matrix logarithm via inverse scaling and squaring', 'Linear Algebra')
doc('sqrtm', 'sqrtm(A)', 'Matrix square root via Denman-Beavers iteration', 'Linear Algebra')
doc('eig_full', '[V,D] = eig_full(A)', 'Full eigendecomposition: A*V = V*D (returns {V, D} cell)', 'Linear Algebra')
doc('svd_full', '[U,S,V] = svd_full(A)', 'Full SVD decomposition (returns {U, S, V} cell)', 'Linear Algebra')
doc('null_space', 'N = null_space(A)', 'Null space of matrix via SVD', 'Linear Algebra')

// Signal Processing
doc('hamming', 'hamming(n)', 'Hamming window of length n', 'Signal Processing')
doc('hanning', 'hanning(n)', 'Hanning (Hann) window of length n', 'Signal Processing')
doc('blackman', 'blackman(n)', 'Blackman window of length n', 'Signal Processing')
doc('kaiser', 'kaiser(n, beta)', 'Kaiser window with parameter beta', 'Signal Processing')
doc('bartlett', 'bartlett(n)', 'Bartlett (triangular) window of length n', 'Signal Processing')
doc('pwelch', 'pwelch(x, nfft)', 'Power spectral density via Welch method', 'Signal Processing')
doc('xcorr', 'xcorr(x, y)', 'Cross-correlation of two signals', 'Signal Processing')
doc('hilbert', 'hilbert(x)', 'Analytic signal via Hilbert transform (returns complex)', 'Signal Processing')
doc('histcounts', 'histcounts(x, nbins) or histcounts(x, edges)', 'Histogram bin counts and edges: [counts, edges]', 'Signal Processing')
doc('medfilt1', 'medfilt1(x, n)', '1-D median filter of window length n', 'Signal Processing')
doc('sgolayfilt', 'sgolayfilt(x, order, framelen)', 'Savitzky-Golay polynomial smoothing filter', 'Signal Processing')
doc('spectrogram', 'spectrogram(x, nfft, noverlap, fs)', 'Short-time Fourier transform power spectrogram (lite)', 'Signal Processing')
doc('findpeaks', "findpeaks(x, 'MinPeakProminence', v, ...)", 'Find local peaks; [pks, locs] = findpeaks(...)', 'Signal Processing')
doc('envelope', 'envelope(x)', 'Signal envelope via Hilbert (abs(analytic))', 'Signal Processing')
doc('detrend', 'detrend(x)', 'Remove linear trend from vector', 'Signal Processing')
doc('movmean', 'movmean(x, w)', 'Moving mean over window w', 'Signal Processing')
doc('movmedian', 'movmedian(x, w)', 'Moving median over window w', 'Signal Processing')
doc('movstd', 'movstd(x, w)', 'Moving standard deviation over window w', 'Signal Processing')
doc('resample', 'resample(x, p, q)', 'Resample at rational rate p/q (lite)', 'Signal Processing')
doc('decimate', 'decimate(x, q)', 'Downsample by integer factor q (keep every q-th)', 'Signal Processing')

// Audio
doc('sound', 'sound(y, fs)', 'Play audio signal y at sample rate fs (produces inline audio player)', 'Audio')
doc('sawtooth', 'sawtooth(t)', 'Generate sawtooth wave', 'Audio', ["t = linspace(0, 4*pi, 500); plot(t, sawtooth(t))"])
doc('square', 'square(t, duty)', 'Generate square wave with optional duty cycle', 'Audio')
doc('chirp', 'chirp(t, f0, t1, f1)', 'Generate frequency-swept cosine (chirp) signal', 'Audio', ["t = linspace(0,1,8000); y = chirp(t,0,1,500); sound(y,8000)"])

// Regex
doc('regexp', "regexp(str, pattern)", 'Find pattern matches (returns 1-indexed start positions)', 'String')
doc('regexpi', "regexpi(str, pattern)", 'Case-insensitive regexp', 'String')
doc('regexprep', "regexprep(str, pattern, replacement)", 'Replace pattern matches in string', 'String')

// Number Theory & Math
doc('gcd', 'gcd(a, b)', 'Greatest common divisor', 'Math')
doc('lcm', 'lcm(a, b)', 'Least common multiple', 'Math')
doc('nchoosek', 'nchoosek(n, k)', 'Binomial coefficient C(n,k)', 'Math')
doc('primes', 'primes(n)', 'All primes up to n (Sieve of Eratosthenes)', 'Math')
doc('isprime', 'isprime(n)', 'Test if n is prime', 'Math')
doc('factor', 'factor(n)', 'Prime factorization of n', 'Math')
doc('deg2rad', 'deg2rad(x)', 'Convert degrees to radians', 'Math')
doc('rad2deg', 'rad2deg(x)', 'Convert radians to degrees', 'Math')
doc('hypot', 'hypot(a, b)', 'Hypotenuse sqrt(a^2+b^2) without overflow', 'Math')

// Timing
doc('timeit', 'timeit(@fn)', 'Benchmark function handle, reports average time', 'Utility')
doc('now', 'now', 'Current date/time as serial date number', 'Utility')
doc('datestr', "datestr(datenum)", 'Convert date number to string', 'Utility')
doc('clock', 'clock', 'Current date/time as [Y M D H M S] vector', 'Utility')
doc('subplot', 'subplot(rows, cols, idx)', 'Create subplot in grid layout', 'Plotting')
doc('text', "text(x, y, 'str')", 'Add text annotation at (x,y) on plot', 'Plotting')
doc('surf', 'surf(X, Y, Z)', '3D surface plot with Viridis colormap and mouse rotation', '3D Plotting', ["[X,Y]=meshgrid(linspace(-2,2,30)); Z=sin(X.^2+Y.^2); surf(X,Y,Z)"])
doc('mesh', 'mesh(X, Y, Z)', '3D wireframe mesh plot with mouse rotation', '3D Plotting')
doc('contour', 'contour(X, Y, Z)', '2D contour plot with marching squares', '3D Plotting')
doc('plot3', 'plot3(x, y, z)', '3D parametric line plot', '3D Plotting', ["t=linspace(0,10*pi,500); plot3(cos(t),sin(t),t)"])
doc('to_python', "to_python('code')", 'Transpile MatFree code to Python (NumPy/SciPy/matplotlib)', 'Utility')
doc('to_julia', "to_julia('code')", 'Transpile MatFree code to Julia', 'Utility')

export function getHelp(name: string): HelpEntry | undefined { return docs.get(name) }
export function getAllHelp(): HelpEntry[] { return [...docs.values()] }
export function searchHelp(query: string): HelpEntry[] {
  const q = query.toLowerCase()
  return [...docs.values()].filter(d =>
    d.name.toLowerCase().includes(q) ||
    d.description.toLowerCase().includes(q) ||
    d.category.toLowerCase().includes(q)
  )
}
export function getCategories(): string[] {
  return [...new Set([...docs.values()].map(d => d.category))]
}
