// MatFree Engine - Public API
export { Interpreter } from './interpreter'
export { Lexer, LexerError } from './lexer'
export { Parser, ParseError } from './parser'
export { Value, Matrix, RuntimeError } from './value'
export { Environment } from './environment'
export { allBuiltinNames } from './builtins'
export { getHelp, getAllHelp, searchHelp, getCategories } from './help'
export type { HelpEntry } from './help'
export type { OutputCallback } from './interpreter'
export type { PlotFigure, PlotSeries, PlotCallback } from './plot'
export { createFigure, PALETTE } from './plot'
export { allSymbolicNames, symToString, parseSym, differentiate, integrate, simplify, expand, solveSymbolic, taylor } from './symbolic'
export { allAdvancedNames } from './advanced'
export { toPython, toJulia } from './transpiler'
export { Debugger } from './debugger'
export type { DebugSnapshot, BreakpointInfo, DebugAction, DebugState } from './debugger'
